version: 0.2

phases:
  build:
    commands:
      - |
        sam build \
          --region "${AWS_REGION}" \
          --template template.yaml
  post_build:
    commands:
      - |
        for region_name in ${TARGET_REGIONS}; do
          sam package \
            --region "${AWS_REGION}" \
            --s3-bucket "subzero-workshop-${region_name}-${ACCOUNT_ID}" \
            --output-template-file "packaged-${region_name}.yaml"
        done
artifacts:
  type: zip
  files:
    - packaged-*.yaml
