AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Conditions:

  NullCondition: !Equals [ 'true', 'false' ]

Resources:

  NullResource:
    Type: Custom::Null
    Condition: NullCondition
