AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:

  AppName:
    Type: String
    AllowedPattern: '^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$'
    MaxLength: 63

  RegionalCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /workshop/regional_certificate_arn

  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /workshop/hosted_zone_id

  UserPoolArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /workshop/cognito_pool_arn

Globals:
  Function:
    Runtime: python3.8
    Handler: index.lambda_handler

Resources:

# API Resources

  WorkshopApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      OpenApiVersion: '3.0.2'
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            AuthorizationScopes:
              - "workshop-api/allow"

  Upload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/post_image
      Events:
        PostImage:
          Type: Api
          Properties:
            Path: /api/images
            Method: post
            RestApiId: !Ref WorkshopApi
#            AuthorizationScopes:
#              - "workshop-api/allow"

  List:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_images
      Events:
        GetImages:
          Type: Api
          Properties:
            Path: /api/images
            Method: get
            RestApiId: !Ref WorkshopApi

# Route 53 Domain Resources

  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub "${AppName}.workshop.dev.jamfnimbus.cloud"
      RegionalCertificateArn: !Ref RegionalCertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiBasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiCustomDomain
      RestApiId: !Ref WorkshopApi
      Stage: Prod
    DependsOn:
      - WorkshopApi
      - WorkshopApiProdStage
      - ApiCustomDomain

  RegionalRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${AppName}.workshop.dev.jamfnimbus.cloud"
      SetIdentifier: !Sub '${AppName}-${AWS::Region}'
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Region: !Ref AWS::Region
      Type: A
