AWSTemplateFormatVersion: 2010-09-09
Description: Deployment Resources

Resources:

  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub 'subzero-workshop-${AWS::Region}-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: 30 day Lifecycle
            Prefix: /
            Status: Enabled
            ExpirationInDays: '30'
      VersioningConfiguration:
        Status: Enabled
