AWSTemplateFormatVersion: 2010-09-09
Description: SSM Parameters for Workshop Templates

Parameters:

  CognitoPoolArn:
    Type: String

  CognitoPoolId:
    Type: String

Resources:

  CognitoPoolArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/cognito_pool_arn
      Type: String
      Value: !Ref CognitoPoolArn

  CognitoPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/cognito_pool_id
      Type: String
      Value: !Ref CognitoPoolId
