AWSTemplateFormatVersion: 2010-09-09
Description: SSM Parameters for Workshop Templates

Parameters:

  HostedZoneId:
    Type: String

  CognitoPoolArn:
    Type: String

  CognitoPoolId:
    Type: String

Resources:

  RegionalCertificateLookup:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      Handler: index.lambda_handler
      Role: !GetAtt RegionalCertificateLookupRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          client = boto3.client('acm')

          def lambda_handler(event, context):
              certificate_arn = None
              response = client.list_certificates(CertificateStatuses=['ISSUED'])
              for item in response['CertificateSummaryList']:
                  if item['DomainName'] == event['ResourceProperties']['DomainName']:
                      certificate_arn = item['CertificateArn']
              try:
                  cfnresponse.send(
                      event, context, cfnresponse.SUCCESS, {'Arn': certificate_arn}
                  )
              except Exception as error:
                  cfnresponse.send(
                      event, context, cfnresponse.FAILED, {'Error': type(error).__name__, 'Message': str(error)}
                  )

  RegionalCertificateLookupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ListCertificates
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: acm:ListCertificates
                Resource: '*'

  RegionalCertificate:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt RegionalCertificateLookup.Arn
      DomainName: '*.workshop.dev.jamfnimbus.cloud'

  RegionalCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/regional_certificate_arn
      Type: String
      Value: !GetAtt RegionalCertificate.Arn

  HostedZoneIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/hosted_zone_id
      Type: String
      Value: !Ref HostedZoneId

  CognitoPoolArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/cognito_pool_arn
      Type: String
      Value: !Ref CognitoPoolArn

  CognitoPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /workshop/cognito_pool_id
      Type: String
      Value: !Ref CognitoPoolId
