AWSTemplateFormatVersion: 2010-09-09

Parameters:

  DomainPrefix:
    Type: String
    Default: jamf-workshop

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref AWS::StackName

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref DomainPrefix

  WorkshopApi:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: workshop-api
      Name: WorkshopApi
      UserPoolId: !Ref UserPool
      Scopes:
        - ScopeName: allow
          ScopeDescription: Default scope
        - ScopeName: custom1
          ScopeDescription: Custom scope 1
        - ScopeName: custom2
          ScopeDescription: Custom scope 2

  TestClient1:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - WorkshopApi
    Properties:
      ClientName: !Sub "${AWS::StackName}-test-client-1"
      GenerateSecret: True
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - workshop-api/allow

  TestClient2:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - WorkshopApi
    Properties:
      ClientName: !Sub "${AWS::StackName}-test-client-2"
      GenerateSecret: True
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - workshop-api/allow
        - workshop-api/custom1

  TestClient3:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - WorkshopApi
    Properties:
      ClientName: !Sub "${AWS::StackName}-test-client-3"
      GenerateSecret: True
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthScopes:
        - workshop-api/allow
        - workshop-api/custom1
        - workshop-api/custom2

  AppleIdLoginClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - WorkshopApi
    Properties:
      ClientName: appleid-logins
      RefreshTokenValidity: 30
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - "http://localhost:8080/login/oauth2/code/cognito"
      LogoutURLs:
        - "http://localhost:8080/logout"
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - workshop-api/allow
